import asyncio
import json
import re
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from ctransformers import AutoModelForCausalLM

print("Loading LLM (TinyLlama 1.1B)...")
llm = AutoModelForCausalLM.from_pretrained(
    "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
    model_file="tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
    model_type="llama"
)
print("LLM loaded")


def ask_llm(prompt: str, max_tokens: int = 512, temperature: float = 0.3) -> str:
    return llm(prompt, max_new_tokens=max_tokens, temperature=temperature)


def extract_json(text: str) -> dict:
    match = re.search(r'\{.*\}', text, re.DOTALL)
    if match:
        return json.loads(match.group())
    raise ValueError("No JSON found")


TOOLS = {
    "get_latest_tag": {"params": {}},
    "get_all_tags": {"params": {}},
    "get_commits_since_tag": {"params": {"tag": "string"}},
    "create_github_release": {"params": {"tag": "string", "title": "string", "notes": "string", "draft": "boolean"}},
    "get_open_pull_requests": {"params": {}},
    "get_current_branch": {"params": {}},
}

TOOLS_DESC = json.dumps(TOOLS, indent=2)


async def call_tool(session: ClientSession, tool_name: str, args: dict) -> str:
    result = await session.call_tool(tool_name, arguments=args)
    return result.content[0].text if result.content else "No result"


def decide_tool(session_context: str, user_request: str) -> dict:
    prompt = f"""You are a release automation assistant. Choose a tool to call.

Available tools:
{TOOLS_DESC}

Context:
{session_context}

User request: {user_request}

Respond with JSON only: {{"tool": "tool_name", "args": {{"param": "value"}}}}"""
    response = ask_llm(prompt, max_tokens=200, temperature=0.1)
    try:
        return extract_json(response)
    except (json.JSONDecodeError, ValueError):
        return {"tool": "get_latest_tag", "args": {}}


def generate_changelog(commits_data: str) -> str:
    prompt = f"""Analyze these git commits and generate a changelog in Markdown format.

Categorize each commit:
- ## Features (feat, add, new)
- ## Bug Fixes (fix, bug, resolve)
- ## Changes (refactor, update, change, improve)
- ## Other

Commits:
{commits_data}

Generate changelog (Markdown, no explanation):"""
    return ask_llm(prompt, max_tokens=512, temperature=0.3).strip()


def suggest_version(current_tag: str, changelog: str) -> str:
    prompt = f"""Current version: {current_tag}

Changelog:
{changelog}

Suggest next semantic version (MAJOR.MINOR.PATCH):
- MAJOR: breaking changes
- MINOR: new features
- PATCH: bug fixes

Respond with version only (e.g., v1.2.3):"""
    response = ask_llm(prompt, max_tokens=50, temperature=0.1).strip()
    match = re.search(r'v?\d+\.\d+\.\d+', response)
    return match.group() if match else "v0.0.1"


async def run_release_pipeline(dry_run: bool = True):
    server_params = StdioServerParameters(
        command="python",
        args=["mcp_github_server.py"]
    )

    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            print("\n=== Step 1: Getting repository state ===")
            branch = await call_tool(session, "get_current_branch", {})
            print(f"Branch: {branch}")

            latest_tag_result = await call_tool(session, "get_latest_tag", {})
            print(f"Latest tag: {latest_tag_result}")

            tags = await call_tool(session, "get_all_tags", {})
            print(f"All tags: {tags[:200]}")

            context = f"Branch: {branch}\nLatest tag: {latest_tag_result}\nAll tags: {tags[:500]}"

            print("\n=== Step 2: Getting commits since last tag ===")
            tag = latest_tag_result if "No tags" not in latest_tag_result else ""
            if tag:
                commits = await call_tool(session, "get_commits_since_tag", {"tag": tag})
            else:
                commits = await call_tool(session, "get_commits_since_tag", {"tag": "HEAD~10"})
            print(f"Commits:\n{commits[:500]}")

            print("\n=== Step 3: AI generating changelog ===")
            changelog = generate_changelog(commits)
            print(f"\nChangelog:\n{changelog}")

            print("\n=== Step 4: AI suggesting version ===")
            new_version = suggest_version(tag if tag else "v0.0.0", changelog)
            print(f"Suggested version: {new_version}")

            release_title = f"Release {new_version}"
            release_notes = f"## {new_version}\n\n{changelog}\n\n---\n*Generated by AI Release Assistant*"

            print(f"\n=== Step 5: {'DRY RUN' if dry_run else 'CREATING'} release ===")
            print(f"Title: {release_title}")
            print(f"Notes:\n{release_notes}")

            if not dry_run:
                result = await call_tool(session, "create_github_release", {
                    "tag": new_version,
                    "title": release_title,
                    "notes": release_notes,
                    "draft": True
                })
                print(f"\nResult: {result}")
            else:
                print("\n(Dry run — no release created. Pass dry_run=False to create.)")

            return {
                "version": new_version,
                "changelog": changelog,
                "commits": commits,
                "tag": tag
            }


if __name__ == "__main__":
    result = asyncio.run(run_release_pipeline(dry_run=True))
