import subprocess
import json
import re
from ctransformers import AutoModelForCausalLM

print("Loading LLM (TinyLlama 1.1B)...")
llm = AutoModelForCausalLM.from_pretrained(
    "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
    model_file="tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
    model_type="llama"
)
print("LLM loaded\n")


def run_cmd(cmd: list[str]) -> str:
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        return f"Error: {e.stderr.strip()}"


def get_current_branch() -> str:
    return run_cmd(["git", "branch", "--show-current"])


def get_latest_tag() -> str:
    result = run_cmd(["git", "describe", "--tags", "--abbrev=0"])
    return result if "Error" not in result else "No tags found"


def get_commits_since_tag(tag: str) -> list[dict]:
    if tag == "No tags found":
        commits_range = "HEAD"
    else:
        commits_range = f"{tag}..HEAD"
    
    result = run_cmd(["git", "log", commits_range, "--pretty=format:%h|%s|%an|%ad", "--date=short", "-20"])
    if "Error" in result or not result:
        return []
    
    commits = []
    for line in result.split("\n"):
        parts = line.split("|")
        if len(parts) == 4:
            commits.append({
                "hash": parts[0],
                "message": parts[1],
                "author": parts[2],
                "date": parts[3]
            })
    return commits


def ask_llm(prompt: str, max_tokens: int = 512, temperature: float = 0.3) -> str:
    return llm(prompt, max_new_tokens=max_tokens, temperature=temperature)


def generate_changelog(commits: list[dict]) -> str:
    if not commits:
        return "No commits to analyze."
    
    commits_text = "\n".join([f"- {c['message']} ({c['hash']})" for c in commits])
    
    prompt = f"""Analyze these git commits and generate a changelog in Markdown format.

Categorize each commit:
- ## Features (feat, add, new)
- ## Bug Fixes (fix, bug, resolve)
- ## Changes (refactor, update, change, improve)
- ## Other

Commits:
{commits_text}

Generate changelog (Markdown, no explanation):"""
    return ask_llm(prompt, max_tokens=512, temperature=0.3).strip()


def suggest_version(current_tag: str, changelog: str) -> str:
    prompt = f"""Current version: {current_tag}

Changelog:
{changelog}

Suggest next semantic version (MAJOR.MINOR.PATCH):
- MAJOR: breaking changes
- MINOR: new features
- PATCH: bug fixes

Respond with version only (e.g., v1.2.3):"""
    response = ask_llm(prompt, max_tokens=50, temperature=0.1).strip()
    match = re.search(r'v?\d+\.\d+\.\d+', response)
    return match.group() if match else "v0.0.1"


def run_release_pipeline():
    print("=" * 60)
    print("  AI Release Assistant")
    print("=" * 60)
    print()
    
    print("Step 1: Getting repository state...")
    branch = get_current_branch()
    print(f"  Branch: {branch}")
    
    latest_tag = get_latest_tag()
    print(f"  Latest tag: {latest_tag}")
    print()
    
    print("Step 2: Getting commits...")
    commits = get_commits_since_tag(latest_tag)
    print(f"  Found {len(commits)} commits")
    if commits:
        print(f"  Latest: {commits[0]['message']}")
    print()
    
    print("Step 3: AI generating changelog...")
    changelog = generate_changelog(commits)
    print(f"\n{changelog}\n")
    
    print("Step 4: AI suggesting version...")
    new_version = suggest_version(latest_tag if latest_tag != "No tags found" else "v0.0.0", changelog)
    print(f"  Suggested version: {new_version}")
    print()
    
    print("=" * 60)
    print("  Release Preview")
    print("=" * 60)
    print(f"Tag: {new_version}")
    print(f"Title: Release {new_version}")
    print(f"\nRelease Notes:\n")
    print(f"## {new_version}\n")
    print(changelog)
    print("\n---")
    print("*Generated by AI Release Assistant*")
    print()
    print("(Dry run — no release created)")
    
    return {
        "version": new_version,
        "changelog": changelog,
        "commits": commits,
        "tag": latest_tag
    }


if __name__ == "__main__":
    run_release_pipeline()
